/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

import com.informatica.powercenter.sdk.mapfwk.core.Field;

/**
 *
 * @author Administrator
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
public class Connector {

    protected String frominstance;
    protected int frominstancetype;
    protected String fromfield;
    protected String toinstance;
    protected int toinstancetype;
    protected String tofield;
    protected Field from;

    public Field getFrom() {
        return from;
    }

    public void setFrom(Field from) {
        this.from = from;
    }

    public Field getTo() {
        return to;
    }

    public void setTo(Field to) {
        this.to = to;
    }
    protected Field to;

    public Connector() {
    }
    
    public Connector(Field from, Field to, String finst, String tinst, int finstt, int tinstt) {
        this.from = from;
        this.to = to;
        this.fromfield=from.getName();
        this.frominstance=finst;
        this.frominstancetype=finstt;
        this.tofield=to.getName();
        this.toinstance=tinst;
        this.toinstancetype=tinstt;
    }
    
    public Connector(Field from, Field to, String finst, int finstt) {
        this.from = from;
        this.to = to;
        this.fromfield=from.getName();
        this.frominstance=finst;
        this.frominstancetype=finstt;
        this.tofield=to.getName();
        this.toinstance=finst;
        this.toinstancetype=finstt;
    }

    /**
     * Gets the value of the frominstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFROMINSTANCE() {
        return frominstance;
    }

    /**
     * Sets the value of the frominstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFROMINSTANCE(String value) {
        this.frominstance = value;
    }

    /**
     * Gets the value of the frominstancetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public int getFROMINSTANCETYPE() {
        return frominstancetype;
    }

    /**
     * Sets the value of the frominstancetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFROMINSTANCETYPE(int value) {
        this.frominstancetype = value;
    }

    /**
     * Gets the value of the fromfield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFROMFIELD() {
        return fromfield;
    }

    /**
     * Sets the value of the fromfield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFROMFIELD(String value) {
        this.fromfield = value;
    }

    /**
     * Gets the value of the toinstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOINSTANCE() {
        return toinstance;
    }

    /**
     * Sets the value of the toinstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOINSTANCE(String value) {
        this.toinstance = value;
    }

    /**
     * Gets the value of the toinstancetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public int getTOINSTANCETYPE() {
        return toinstancetype;
    }

    /**
     * Sets the value of the toinstancetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOINSTANCETYPE(int value) {
        this.toinstancetype = value;
    }

    /**
     * Gets the value of the tofield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOFIELD() {
        return tofield;
    }

    /**
     * Sets the value of the tofield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOFIELD(String value) {
        this.tofield = value;
    }
}
